# Pandas Creating & Reading CSV files

In [ ]:
import pandas as pd

In [ ]:
data = pd.DataFrame({
    'Name' : ['Ankit', 'Aishwarya', 'Sanket', 'Shivangi', 'Saiprasad', 'Rishika', 'Pratiksha'],
    'Age' : [23, 21, 22, 21, 22, 21, 20],
    'University' : ['BHU', 'JNU', 'DU', 'BHU', 'SPPU', 'SPPU', 'DU'],
})

In [ ]:
data

        Name  Age University
0      Ankit   23        BHU
1  Aishwarya   21        JNU
2     Sanket   22         DU
3   Shivangi   21        BHU
4  Saiprasad   22       SPPU
5    Rishika   21       SPPU
6  Pratiksha   20         DU

In [ ]:
# data.to_csv('students.csv')
data.to_csv('students.csv', index = False)

# Uploading Datasets

In [ ]:
students = pd.read_csv('/content/students.csv')

In [ ]:
students

        Name  Age University
0      Ankit   23        BHU
1  Aishwarya   21        JNU
2     Sanket   22         DU
3   Shivangi   21        BHU
4  Saiprasad   22       SPPU
5    Rishika   21       SPPU
6  Pratiksha   20         DU

# Groupby Function

In [ ]:
emp = pd.read_csv('/content/Employees.csv')

In [ ]:
emp

,Unnamed: 0,Name,Department,Employment Type,Salary,Years of Experience
0,0,Asha,Administration,Full-time Employee,120000,5
1,1,Harsh,Marketing,Intern,50000,1
2,2,Sourav,Technical,Intern,70000,2
3,3,Riya,Technical,Part-time Employee,70000,3
4,4,Hritik,Marketing,Part-time Employee,55000,4
5,5,Shivansh,Administration,Full-time Employee,120000,7
6,6,Rohan,Technical,Full-time Employee,125000,6
7,7,Akash,Marketing,Intern,60000,2
8,8,Soumya,Technical,Intern,50000,1
9,9,Kartik,Administration,Full-time Employee,120000,6

In [ ]:
grouped = emp.groupby('Department')

tech = grouped.get_group('Technical')
market = grouped.get_group('Marketing')
admin = grouped.get_group('Administration')

In [ ]:
market
# market['Salary'].mean()

,Unnamed: 0,Name,Department,Employment Type,Salary,Years of Experience
1,1,Harsh,Marketing,Intern,50000,1
4,4,Hritik,Marketing,Part-time Employee,55000,4
7,7,Akash,Marketing,Intern,60000,2

In [ ]:
market['Years of Experience'].mean()

2.3333333333333335

In [ ]:
admin

,Unnamed: 0,Name,Department,Employment Type,Salary,Years of Experience
0,0,Asha,Administration,Full-time Employee,120000,5
5,5,Shivansh,Administration,Full-time Employee,120000,7
9,9,Kartik,Administration,Full-time Employee,120000,6

# Top Commands

Creating New, Renaming & Droping Columns.

Apply Method, Sort Index, Sort Values.

In [ ]:
data

        Name  Age University
0      Ankit   23        BHU
1  Aishwarya   21        JNU
2     Sanket   22         DU
3   Shivangi   21        BHU
4  Saiprasad   22       SPPU
5    Rishika   21       SPPU
6  Pratiksha   20         DU

**Creating New Columns**

In [ ]:
# Creating New Columns

data['City'] = ['Delhi', 'Bangalore', 'Chennai', 'Patna', 'Pune', 'Pune', 'Mumbai']

In [ ]:
data

        Name  Age University       City
0      Ankit   23        BHU      Delhi
1  Aishwarya   21        JNU  Bangalore
2     Sanket   22         DU    Chennai
3   Shivangi   21        BHU      Patna
4  Saiprasad   22       SPPU       Pune
5    Rishika   21       SPPU       Pune
6  Pratiksha   20         DU     Mumbai

**Renaming Columns**

In [ ]:
data.columns = ['First Name','Current Age','College University','Location']

In [ ]:
data

  First Name  Current Age College University   Location
0      Ankit           23                BHU      Delhi
1  Aishwarya           21                JNU  Bangalore
2     Sanket           22                 DU    Chennai
3   Shivangi           21                BHU      Patna
4  Saiprasad           22               SPPU       Pune
5    Rishika           21               SPPU       Pune
6  Pratiksha           20                 DU     Mumbai

**Droping Columns**

In [ ]:
data.drop(['Current Age'], axis = 1)           # Temporary Droping Syntax

  First Name College University   Location
0      Ankit                BHU      Delhi
1  Aishwarya                JNU  Bangalore
2     Sanket                 DU    Chennai
3   Shivangi                BHU      Patna
4  Saiprasad               SPPU       Pune
5    Rishika               SPPU       Pune
6  Pratiksha                 DU     Mumbai

In [ ]:
data

  First Name  Current Age College University   Location
0      Ankit           23                BHU      Delhi
1  Aishwarya           21                JNU  Bangalore
2     Sanket           22                 DU    Chennai
3   Shivangi           21                BHU      Patna
4  Saiprasad           22               SPPU       Pune
5    Rishika           21               SPPU       Pune
6  Pratiksha           20                 DU     Mumbai

In [ ]:
data.drop(['Current Age'], axis = 1, inplace = True)           # Permanent Droping Syntax

In [ ]:
data

  First Name College University   Location
0      Ankit                BHU      Delhi
1  Aishwarya                JNU  Bangalore
2     Sanket                 DU    Chennai
3   Shivangi                BHU      Patna
4  Saiprasad               SPPU       Pune
5    Rishika               SPPU       Pune
6  Pratiksha                 DU     Mumbai

In [ ]:
data

  First Name College University   Location
0      Ankit                BHU      Delhi
1  Aishwarya                JNU  Bangalore
2     Sanket                 DU    Chennai
3   Shivangi                BHU      Patna
4  Saiprasad               SPPU       Pune
5    Rishika               SPPU       Pune
6  Pratiksha                 DU     Mumbai

**Apply Method**

In [ ]:
# Creating Marks Column

data['Marks'] = [201, 210, 195, 183, 225, 203, 190]

In [ ]:
data

  First Name College University   Location  Marks
0      Ankit                BHU      Delhi    201
1  Aishwarya                JNU  Bangalore    210
2     Sanket                 DU    Chennai    195
3   Shivangi                BHU      Patna    183
4  Saiprasad               SPPU       Pune    225
5    Rishika               SPPU       Pune    203
6  Pratiksha                 DU     Mumbai    190

In [ ]:
# Apply Method

data['Marks'] = data['Marks'].apply(lambda x: x/5)

In [ ]:
data

  First Name College University   Location  Marks
0      Ankit                BHU      Delhi   40.2
1  Aishwarya                JNU  Bangalore   42.0
2     Sanket                 DU    Chennai   39.0
3   Shivangi                BHU      Patna   36.6
4  Saiprasad               SPPU       Pune   45.0
5    Rishika               SPPU       Pune   40.6
6  Pratiksha                 DU     Mumbai   38.0

In [ ]:
# Renaming Column

data.columns = ['First Name','College University','Location', 'Marks/Subject']

In [ ]:
data

  First Name College University   Location  Marks/Subject
0      Ankit                BHU      Delhi           40.2
1  Aishwarya                JNU  Bangalore           42.0
2     Sanket                 DU    Chennai           39.0
3   Shivangi                BHU      Patna           36.6
4  Saiprasad               SPPU       Pune           45.0
5    Rishika               SPPU       Pune           40.6
6  Pratiksha                 DU     Mumbai           38.0

**Sort Index**

In [ ]:
data.index = [10,28,64,7,1,6,15]          # Assigning Index

In [ ]:
data

   First Name College University   Location  Marks/Subject
10      Ankit                BHU      Delhi           40.2
28  Aishwarya                JNU  Bangalore           42.0
64     Sanket                 DU    Chennai           39.0
7    Shivangi                BHU      Patna           36.6
1   Saiprasad               SPPU       Pune           45.0
6     Rishika               SPPU       Pune           40.6
15  Pratiksha                 DU     Mumbai           38.0

In [ ]:
data.sort_index(ascending = True)                      # Default Statement : Ascending = True

   First Name College University   Location  Marks/Subject
1   Saiprasad               SPPU       Pune           45.0
6     Rishika               SPPU       Pune           40.6
7    Shivangi                BHU      Patna           36.6
10      Ankit                BHU      Delhi           40.2
15  Pratiksha                 DU     Mumbai           38.0
28  Aishwarya                JNU  Bangalore           42.0
64     Sanket                 DU    Chennai           39.0

In [ ]:
data.sort_index(ascending = False)

   First Name College University   Location  Marks/Subject
64     Sanket                 DU    Chennai           39.0
28  Aishwarya                JNU  Bangalore           42.0
15  Pratiksha                 DU     Mumbai           38.0
10      Ankit                BHU      Delhi           40.2
7    Shivangi                BHU      Patna           36.6
6     Rishika               SPPU       Pune           40.6
1   Saiprasad               SPPU       Pune           45.0

**Sort Values**

In [ ]:
data.sort_values(by = 'Marks/Subject', ascending = False)

   First Name College University   Location  Marks/Subject
1   Saiprasad               SPPU       Pune           45.0
28  Aishwarya                JNU  Bangalore           42.0
6     Rishika               SPPU       Pune           40.6
10      Ankit                BHU      Delhi           40.2
64     Sanket                 DU    Chennai           39.0
15  Pratiksha                 DU     Mumbai           38.0
7    Shivangi                BHU      Patna           36.6